kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node:14-alpine
  commands:
  - npm install
  - npm test
- name: codecov
  image: robertstettner/drone-codecov
  settings:
    token: 
      from_secret: codecov_secret